sources/niUI/src/Line.cpp, sources/niUI/tsrc_ni/EditBox.gml
This PR fixes: 
* RN: niUI: EditBox widget, fixed an issue with Chinese (and Unicode) characters that were not cut correctly ;
*
*
```
ham Run_Test_niScript_tu_linter
```
=> niUI/Line.cpp: EditBox: Fixed a problem that Chinese character didn't cut correctly ;

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/main.yml, sources/niLang/tsrc/Test_AccurateSleep.cpp
This PR fixes:
* NoRN: niLang/tsrc/Test_AccurateSleep.cpp: Fixed tolerance to take into account difference in CI.
* RN:
* RN:
Link to issue: Fixes ?
Link to reference doc: ?
```
ham Run_Test_niLang FIXTURE=FAccurateSleep
```
=> niLang/tsrc/Test_AccurateSleep.cpp: Fixed tolerance to take into account difference in CI.

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/main.yml, sources/niLang/tsrc/Test_AccurateSleep.cpp, sources/niUI/src/Canvas.cpp
Fixed Canvas bug with LineGrid API's
This PR fixes:
* RN: niUI: Fixed rounding issue with iCanvas::LineGridXY and iCanvas::LineGridXZ ;
```
rdd-run rdd-application-blockout preview $RDD_REPO/data/rdd-application-blockout/rot/level_demo.csv
```
=> niUI: Fixed Canvas bug with LineGrid API's

sources/niLang/src/API/niLang/Platforms/Win32/Win32_DelayLoadImpl.h, sources/niLang/src/API/niLang/Utils/ModuleDefImpl_End.h, sources/niUI/src/API/niUI/Utils/AABB.h, sources/niUI/src/UIContext.cpp
This PR fixes:
* RN: niLang: Fixed compilation error & deadlock on MSVC 19. 
* RN:
* RN:
Fixed compilation error & deadlock on MSVC 19. 
See https://gist.github.com/prenaux/0fd3157abbf15e4cad6db733d0516bac & https://godbolt.org/z/o8rWsWsbb for the details.
```
ham Run_ci
```
=> Fix MSVC19 compilation issues ;

sources/niLang/src/API/niLang/STL/non_null.h, sources/niLang/src/API/niLang/Utils/Nonnull.h, sources/niLang/src/API/niLang/Utils/QPtr.h, sources/niLang/src/API/niLang/Utils/SmartPtr.h, sources/niLang/src/API/niLang/Utils/WeakPtr.h, sources/niLang/src/DataTable.cpp, sources/niLang/src/System_Metal.mm, sources/niLang/tsrc/Test_WeakPtr.cpp, sources/niScript/src/sqbaselib.cpp, sources/niScript/src/sqclosure.h, sources/niScript/src/sqvm_exec.cpp, sources/niUI/src/Bitmap2D.cpp, sources/niUI/src/EditorBuffer.cpp, sources/niUI/src/Font.cpp, sources/niUI/src/TextObject.cpp, sources/niUI/src/UIContext.cpp, sources/niUI/src/UIContext_Drag.cpp, sources/niUI/src/UIContext_Focus.cpp, sources/niUI/src/UIContext_Input.cpp, sources/niUI/src/Widget.cpp, sources/niUI/src/WidgetForm.cpp, sources/niUI/src/WidgetTree.cpp, sources/niUI/tsrc/Test_RT.cpp, sources/niUnitTest/src/UnitTestAppLib.cpp
This PR fixes:
* RN:
* RN:
* RN:
[Open diagram](https://mermaid.live/edit?gist=#pako:eNqlU91rwjAQ_1dChnsQ275XEba5tzF0duyhGRLt2XatSUlTRMT_fZc26YS6vQz6cbn8PpI77kx3MgEa0tGIZFpXdRgEB1AHnifeV-2nuc6arZ9Llwzugn0pj7uMK81EqniVkWgxZYLggxprzUXCVUKiUwU15vJ3UQh5FFHcR-Fsq4K5W44_DXspc6FBRbELOlA0npAavSDZVFoZZGfjyGSpVW-FcYxvS5z9GM9bg5XZXf26_QG8MAj7vwnqrF-lEE1Z9q52HTNqowGX0dZCSLGxSF7rMgxdwhLczYklIKVutl2JXyAFkWDmgXj-ExdkC8RQfW9OHqdd3rP-nsu1jGuVdJM3tm59N7p7fF53Ci1QwlQWvTLYFVbYZN3tjUlPmA7Zq__RbRtwwegCFOzJfVulaz1G_1QcSHR4c7CbxVH8SOI3_PQF6RsyvIdrXWvrcL0szgKdUDsxOFtnTBFGdQYHYDTEEEekYJSJC-KaKuEanpNcS0XDPS9rmFDeaLk-iR0NtWrAgRY5x8MeLOryDRiOR6w) (visible inline on github)
```mermaid
%% https://mermaid-js.github.io/mermaid/#/flowchart
graph TD;
%% Standard Types …
```
=> Pierre: Cleanup Ptr/QPtr/WeakPtr types.

.github/workflows/main.yml, sources/HelloUI/ios/HelloUI_ios.xcodeproj/project.pbxproj, sources/niCURL/tsrc/Test_GET.cpp, sources/niLang/tsrc/Test_AccurateSleep.cpp, sources/niLang/tsrc/Test_DataTable_Serialize.cpp, sources/niLang/tsrc/Test_HashedDir.cpp, sources/niLang/tsrc/Test_StartPath.cpp, sources/niLang/tsrc/Test_URLFile.cpp, sources/niScript/src/sqstate.cpp, sources/niUI/src/WidgetTree.cpp
This PR fixes:
* RN:
* RN:
* RN:
```
ham Run_ci
```
=> Update .github/workflows/main.yml ;

sources/niLang/src/API/niLang/STL/memory.h, sources/niLang/tsrc/Test_Nonnull.cpp
This PR fixes:
* RN: niLang: Add astl::unique_non_null type.
* RN:
* RN:
```
ham Run_ci
```
=> niLang: Add astl::unique_non_null type ;

sources/HelloUI/cpp/HelloUI_cpp.cpp, sources/HelloUI/ios/HelloUI_ios.xcodeproj/project.pbxproj, sources/HelloUI/ios/HelloUI_ios/HelloUI_ios.cpp, sources/HelloUI/ios/HelloUI_ios/niUIView.mm, sources/HelloUI/rtcpp_main/HelloUI_rtcpp.cpp, sources/ni/src/ni.cpp, sources/niAppLib/src/API/niAppLib.h, sources/niAppLib/src/niAppLib.cpp, sources/niCURL/src/CURL.cpp, sources/niCURL/tsrc/Test_Fetch.cpp, sources/niLang/src/API/niLang/IConcurrent.h, sources/niLang/src/API/niLang/STL/memory.h, sources/niLang/src/API/niLang/STL/non_null.h, sources/niLang/src/API/niLang/STL/optional.h, sources/niLang/src/API/niLang/STL/string.h, sources/niLang/src/API/niLang/STL/utils.h, sources/niLang/src/API/niLang/Utils/ConcurrentImpl.h, sources/niLang/src/API/niLang/Utils/Nonnull.h, sources/niLang/src/API/niLang/Utils/SinkList.h, sources/niLang/src/API/niLang/Utils/SmartPtr.h, sources/niLang/src/API/niLang/Utils/Trace.h, sources/niLang/src/Concurrent.cpp, sources/niLang/src/_idl/IConcurrent.h.idl.xml, sources/niLang/src/_niLang_ModuleDef.xml, sources/niLang/tsrc/Test_Nonnull.cpp, sources/niUI/src/API/niUI/Utils/WidgetSinkImpl.h, sources/niUnitTest/src/API/niUnitTest.h, sources/niUnitTest/src/UnitTestAppLib.cpp
This PR fixes:
* RN:
* RN:
* RN:
```
ham Run_ci
```
=> Make non_null compatible with unique_ptr & more consistent Ptr APIs ;

_ham_project
This PR fixes:
* RN:
* RN:
* RN:
```
. hat
```
=> Fixed _ham_project on Windows

sources/niCURL/src/CURL.cpp, sources/niCURL/tsrc/Test_Fetch.cpp, sources/niLang/src/DataTable_Serialize.cpp, sources/niLang/tsrc/Test_Json.cpp
I partial implementation if a serialization from DataTabnle to JSON. This implementation doesn't take nested JSON into consideration.
```
cd niLang
ham Run_Test_niLang FIXTURE=FJson
```
=> niLang/DataTable_Serialize.cpp: Added a function to serialize a Datable to JSON

sources/niCURL/src/CURL.cpp, sources/niCURL/tsrc/Test_Fetch.cpp
* Link to issue: #54 
There is a level called `http_request_final.vpk`. This level write a text label with the output of a URL Request. If I have an override in the JS it will write the overrided reply. While if I do not have the override OR if I run it from the standalone player (no web) it writes the result of the original request.
The niCURL test had been updated too to test these events:
```
cd niLang
. hat
ham Run_Test_niCURL
```
To test the web version you can follow the same as in pr #54
=> niCURL: Throw the necessary events when the fetch is overriden

_ham_project, sources/_build.ham, sources/niScriptCpp/src/ScriptingHostCpp.cpp, sources/niThrift/_build.ham, sources/niThrift/src/API/niThrift/IThriftClient.h, sources/niThrift/src/API/niThrift/TClientImpl.h, sources/niThrift/src/API/niThrift/TCurlWriterTransport.h, sources/niThrift/src/API/niThrift/TNiFileTransport.h, sources/niThrift/src/API/niThrift/TResultT.h, sources/niThrift/src/API/niThrift/TSeqProtocol.h, sources/niThrift/src/API/niThrift/ThriftUtils.h, sources/niThrift/tsrc/Test_CppNiClient.cpp, sources/niThrift/tsrc/Test_Main.cpp, sources/niThrift/tsrc/_build.ham, sources/niThrift/tsrc/stdafx.cpp, sources/niThrift/tsrc/stdafx.h
Add a niThrift module with a test case that call the ham-test-thrift service.
Its a C++ header only module atm.
```
ham Run_ci
```
=> Add niThrift module ;

.gitattributes, .github/workflows/main.yml, _ham_project, _run_ci.sh, sources/niLang/tsrc/Test_OSXWindow.mm, sources/niScriptCpp/src/ScriptingHostCpp.cpp, sources/niUI/tsrc/_build.ham, sources/niUnitTest/src/API/niUnitTest.h, sources/niUnitTest/src/UnitTest.cpp
=> Run CI on macOS & Windows

.github/workflows/main.yml
=> workflows/main.yml: Checks-out & init ham first ;

sources/emscripten/0_niLang_pre.js, sources/emscripten/0_niLang_shell.html
Now we can pass parameters to the module via the **Params** property. This params behave like the ones coming from the URL query and they can be overriden by the URL query params. Params are a key-value pair. Example:
```js
var Module = createVlkPlayerNiModule({
Params: { OpenFile: vpkFile, /* more params here if your need to */ },
// more module properties
}
```
Now we can also disable the input for the canvas if we want. We must pass **UseInput** boolean property at module creation. This is a mandatory field. Example:
```js
var Module = createVlkPlayerNiModule({
UseInput: false,
// more module properties
}
```
* RN:
* RN:
* NoRN:
You can test it like any other emscripten test
```
BUILD_TARGET=web-js . hat
ham pass1 && ham Test_niLang …
```
=> Javier: niLang: Emscripten params and optional input 

_ham_project, sources/_rules_sdks.ham, sources/niLang/src/Platform_Posix_StackWalker.cpp, sources/niLang/src/_build.ham, sources/niLang/src/backward.hpp, sources/niLang/tsrc/Test_CrashReport.cpp, specs/toolsets/syslib_libdw/setup-toolset.sh
No joke, Ubuntu 22's binutils doesnt read the dwarf info generated by Clang 18 so no source info there xD. So this uses libdw instead which does read them correctly on all platforms I've tried - and the test case actually check for source line on Linux.
That's not critically necessary but since I spent so much time to make sure all this worked I'm not gonna let it go at the last bit... Still fml Linux's toolchains & libraries are a mess, I almost miss Windows' "DLL Hell"...
```
./_run_ci.sh
```
=> Pierre: Linux use libdw to extract source info

.github/workflows/main.yml
=> Cleaned up GH CI workflow and add build for ubuntu24 & macos13.

sources/niLang/src/System_Linux.cpp, sources/niLang/src/ni_dll_sym_x11.h, sources/niLang/tsrc/Test_OSWindow.cpp
This PR does the following:
* Cherry pick some commits from arantir-wip branch to fix the OpenGL driver in windows
* Adds support for mouse capture in X11
* Fixes a compilation error regarding the use of exceptions in CrashReport.h 
* Removes Vulkan headers requirement from Linux and Windows
```
hamx :niLang Run_Test_niLang FIXTURE=FOSWindow,Create
```
With the mouse on top of the windows press "k" to activate the mouse capture. The cursor should disappear and you get debug text printed in the output when moving the mouse. Press "k" again to deactivate the mouse capture and recover the cursor.
Other key bindinds for testing new added features:
* R: Redraw the whole window (equivalent to windows  InvalidateRect)
* M: Moves the window to …
=> niLang: Adds mouse capture to Linux and rebases fix on OpenGL windows

sources/niLang/src/Clipboard.cpp, sources/niLang/src/System_Linux.cpp, sources/niLang/src/ni_dll_sym_x11.h
This PR allows X11 apps to paste content from niLang apps and the other way around (almost, keep reading).
Because  X11 selection system is CRAZY and async the paste functionality doesn't fit in the current niLang implementation that assumes a linear use of the clipboard. In this PR:
```
cd niLang
ham Run_HelloUI_cpp
```
Use the EditBox to to copy & paste. You should be able to paste to another apps like the browser or a text editor. You should not be able to paste from an external app to the niLang app yet.
=> Javier: x11 clipboard support

sources/niLang/src/System_Linux.cpp
Pressed keys could get stuck forever in the niLang X11 state when switching windows. For example, when you were switching out of the niLang window with ALT+TAB the ALT key remained stuck in the niLang state forever. This PR fixes that issue.
```
cd niLang
ham Run_HelloUI_cpp
```
To test that it works: 
1. Select and copy text from the EditBox
2. Switch window with ALT+TAB or by click out of the window while holding any key
3. Go back to the niLang window and paste again in the EditBox with CTRL+V
I the paste is successful means that it works.
=> System_Linux.cpp: prevent keys from getting stuck when window loses focus
